server {
    listen 8080;
    root /usr/share/nginx/html/portal;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}

server {
    listen 8091;
    root /usr/share/nginx/html/snake;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}

server {
    listen 8092;
    root /usr/share/nginx/html/stack;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}

server {
    listen 8093;
    root /usr/share/nginx/html/rocks;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}

server {
    listen 8094;
    root /usr/share/nginx/html/invaders;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}

server {
    listen 8095;
    root /usr/share/nginx/html/2048;
    index index.html;
    add_header X-Xin-Pod $hostname always;
}
